version: '3.9'

services:
  app:
    build: .
    ports:
      - "2300:2300" # ⬅ слушаем правильный порт Hanami
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    command: bundle exec hanami server --host 0.0.0.0 --port 2300

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hodlhodl_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
